server_host: "127.0.0.1"
tests:
  - job: "iperf"
    interface: "en0"          
    parameters:
      proto: "tcp"
      duration_ms: 5000

  - job: "iperf"
    interface: "en0"
    parameters:
      proto: "udp"
      duration_ms: 5000
      bitrate: "10M"

  - job: "irtt"
    interface: "en0"
    parameters:
      frequency_ms: 3
      duration_ms: 5000
